import { EventEmitter } from 'node:events';
import { Model } from 'mongoose';
import type { TopicHubLogger } from '../common/logger';
import { generatePairingCode } from './identity-types';

export interface PairingRotatedPayload {
  code: string;
  expiresAt?: Date;
}

export interface ClaimResult {
  topichubUserId: string;
  platform: string;
  platformUserId: string;
}

export interface ResolvedPlatformUser {
  topichubUserId: string;
  claimToken: string;
}

export interface ResolvedClaimTokenUser {
  topichubUserId: string;
}

export class IdentityService {
  private readonly pairingRotationEmitter = new EventEmitter();

  constructor(
    private readonly bindingModel: Model<any>,
    private readonly pairingCodeModel: Model<any>,
    private readonly logger: TopicHubLogger,
  ) {}

  /**
   * Subscribe to new pairing codes for this executor session (e.g. after a code was leaked in a group chat).
   * `executorToken` must match the value stored as `executorClaimToken` on pairing documents.
   */
  subscribePairingRotations(
    executorToken: string,
    handler: (payload: PairingRotatedPayload) => void,
  ): () => void {
    this.pairingRotationEmitter.on(executorToken, handler);
    return () => {
      this.pairingRotationEmitter.off(executorToken, handler);
    };
  }

  async generateExecutorPairingCode(
    topichubUserId: string,
    executorClaimToken: string,
  ): Promise<{ code: string; expiresAt?: Date }> {
    const existing = await this.pairingCodeModel
      .findOne({ topichubUserId, executorClaimToken, claimed: false })
      .sort({ createdAt: -1 })
      .exec();
    if (existing) {
      this.logger.log(`Reusing pairing code for identity ${topichubUserId}`);
      return { code: existing.code };
    }

    const code = generatePairingCode();
    await this.pairingCodeModel.create({
      code,
      topichubUserId,
      executorClaimToken,
      claimed: false,
    });

    this.logger.log(`Pairing code generated by executor for identity ${topichubUserId}`);
    return { code };
  }

  /**
   * When a valid pairing code is posted in a public channel, mark it used (without creating an IM binding)
   * and issue a fresh code for the same executor session. Notifies subscribers via {@link subscribePairingRotations}.
   */
  async invalidateLeakedPairingCodeAndRotate(
    code: string,
    meta: { platform: string; channel: string },
  ): Promise<{ rotated: boolean; newCode?: string; expiresAt?: Date }> {
    const leakedBy = `leaked_group:${meta.platform}:${meta.channel}`;

    const leaked = await this.pairingCodeModel
      .findOneAndUpdate(
        {
          code,
          claimed: false,
        },
        {
          $set: {
            claimed: true,
            claimedByUserId: leakedBy,
          },
        },
        { new: true },
      )
      .exec();

    if (!leaked) {
      return { rotated: false };
    }

    const { topichubUserId, executorClaimToken } = leaked;
    const fresh = await this.generateExecutorPairingCode(topichubUserId, executorClaimToken);

    const payload: PairingRotatedPayload = { code: fresh.code };
    if (fresh.expiresAt != null) payload.expiresAt = fresh.expiresAt;
    this.pairingRotationEmitter.emit(executorClaimToken, payload);

    this.logger.log(
      `Pairing code invalidated after group leak; rotated for identity ${topichubUserId}`,
    );

    return {
      rotated: true,
      newCode: fresh.code,
      expiresAt: fresh.expiresAt,
    };
  }

  async claimPairingCode(
    platform: string,
    platformUserId: string,
    code: string,
  ): Promise<ClaimResult> {
    const pairingCode = await this.pairingCodeModel
      .findOne({ code, claimed: false })
      .exec();

    if (!pairingCode) {
      throw new Error(`Invalid pairing code: ${code}`);
    }

    const topichubUserId = pairingCode.topichubUserId;
    const claimToken = pairingCode.executorClaimToken;

    await this.bindingModel
      .findOneAndUpdate(
        { platform, platformUserId },
        {
          $set: {
            topichubUserId,
            claimToken,
            active: true,
          },
        },
        { upsert: true, new: true },
      )
      .exec();

    this.logger.log(
      `Pairing code used for binding: code=${code} user=${topichubUserId} platform=${platform}:${platformUserId}`,
    );

    return {
      topichubUserId,
      platform,
      platformUserId,
    };
  }

  async resolveUserByPlatform(
    platform: string,
    platformUserId: string,
  ): Promise<ResolvedPlatformUser | undefined> {
    const binding = await this.bindingModel
      .findOne({ platform, platformUserId, active: true })
      .exec();

    if (!binding) return undefined;

    return {
      topichubUserId: binding.topichubUserId,
      claimToken: binding.claimToken,
    };
  }

  async resolveUserByClaimToken(
    claimToken: string,
  ): Promise<ResolvedClaimTokenUser | undefined> {
    const binding = await this.bindingModel
      .findOne({ claimToken, active: true })
      .exec();

    if (!binding) return undefined;

    return {
      topichubUserId: binding.topichubUserId,
    };
  }

  async deactivateBinding(
    platform: string,
    platformUserId: string,
  ): Promise<boolean> {
    const result = await this.bindingModel
      .findOneAndUpdate(
        { platform, platformUserId, active: true },
        { $set: { active: false } },
      )
      .exec();

    if (result) {
      this.logger.log(`Binding deactivated: ${platform}:${platformUserId}`);
    }

    return result != null;
  }

  async deactivateAllBindings(claimToken: string): Promise<number> {
    const result = await this.bindingModel
      .updateMany(
        { claimToken, active: true },
        { $set: { active: false } },
      )
      .exec();

    if (result.modifiedCount > 0) {
      this.logger.log(`Deactivated ${result.modifiedCount} binding(s) for claimToken`);
    }

    return result.modifiedCount;
  }

  async getBindingsForUser(
    topichubUserId: string,
  ): Promise<any[]> {
    return this.bindingModel
      .find({ topichubUserId, active: true })
      .exec();
  }
}
